// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbMQenSDVmQieXv3Oa6uPS7DWsqtoj6js',
    appId: '1:292080316722:web:94507c250a4af4e339672b',
    messagingSenderId: '292080316722',
    projectId: 'dartguard-ad57a',
    authDomain: 'dartguard-ad57a.firebaseapp.com',
    storageBucket: 'dartguard-ad57a.firebasestorage.app',
    measurementId: 'G-CHX9QNY7QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRYNfog-gqKIz-prcVyHA5Z2gMgsvN_Do',
    appId: '1:292080316722:android:4887fef08d9b9f9f39672b',
    messagingSenderId: '292080316722',
    projectId: 'dartguard-ad57a',
    storageBucket: 'dartguard-ad57a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyslvO0Levyv8l7ve_JoXp67Nrd0ocB60',
    appId: '1:292080316722:ios:55794d894f15f06e39672b',
    messagingSenderId: '292080316722',
    projectId: 'dartguard-ad57a',
    storageBucket: 'dartguard-ad57a.firebasestorage.app',
    iosBundleId: 'com.example.dartGuard',
  );
}
